services:
  - type: web
    name: cambodia-hrms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: 3.12.0
